spring.application.name=solucaoDescarte

spring.datasource.url=jdbc:mysql://localhost:3306/Descarte_De_Residuos
spring.datasource.username=root
spring.datasource.password=1234

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true